config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :users
  resources :chatrooms
  resources :messages
  resources :account_activation, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 	 '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'

  get 	 '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # mount ActionCable.server, at: '/cable'
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def edit
  	# @user = User.find_by(email: params[:email])
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = "Password has been reset."
      redirect_to @user
    else
      render 'edit'
    end  	
  end

  def create
  	@user = User.find_by(email: params[:password_reset][:email].downcase)
  	if @user
  		@user.create_reset_digest
  		@user.send_password_reset_email
  		flash[:info] = "Email sent with password reset instructions"
  		redirect_to root_path
  	else
  		flash.now[:danger] = "Email address not found"
  		render 'new'
  	end
  end


  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # Confirms a valid user.
    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    # Checks expiration of reset token.
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end    
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.slim
= provide(:title, 'Reset password')
= provide(:button_text, 'Reset password')

h1 Reset password
.row
	.col-md-6.col-md-offset-3
		= form_for(@user, url: password_reset_path(params[:id])) do |f|
			- if @user.errors.any?
				.alert the form contains #{pluralize(@user.errors.count, 'error')}
				ul
					- @user.errors.full_messages.each do |e|
						li #{e}

			= hidden_field_tag :email, @user.email

			= f.label :password
			= f.password_field :password, class: "form-control"

			= f.label :password_confirmation
			= f.password_field :password_confirmation, class: "form-control"

			= f.submit yield(:button_text), class: "btn btn-primary"

app/views/password_resets/new.html.slim
= provide(:title, "Reset Password")
h1 Reset password
.row
	.col-md-6.col-md-offset-3
		= form_for(:password_reset, url: password_resets_path) do |f|
			= f.label :email
			= f.email_field :email, class: "form-control"
	
			= f.submit :submit, class: "btn btn-primary"