config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :users
  resources :chatrooms
  resources :messages
  resources :account_activation, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 	 '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'

  get 	 '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # mount ActionCable.server, at: '/cable'
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
	has_many :users, through: :messages
	has_many :messages, dependent: :destroy
	validates :topic, presence: true, uniqueness: true
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
	before_action :require_user_login

	def index
		@chatrooms = Chatroom.all
	end

	def new
		@chatroom = Chatroom.new
	end

	def create
		@chatroom = Chatroom.new(chatroom_params)
		if @chatroom.save
			flash[:success] = "Chatroom created!"
			redirect_to @chatroom
		else
			render 'new'
		end
	end

	def show
		@chatroom = Chatroom.find_by(id: params[:id])
		@message = Message.new
	end

	def destroy
		Chatroom.find_by(id: params[:id]).destroy
		flash[:success] = "Chatroom deleted"
		redirect_to chatrooms_path
	end


	private

		def chatroom_params
			params.require(:chatroom).permit(:topic)
		end	
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_chatroom.html.slim
<li>
	= link_to chatroom.topic, chatroom

	- if current_user.admin?
		|  | 
		= link_to "delete", chatroom, method: :delete,
	                              data: { confirm: "You sure?" }

app/views/chatrooms/index.html.slim
= provide(:title, 'All Chat Rooms!')
h1 All Chat Rooms

.center
	p Don't see any chat rooms you like?
	= link_to "Create a Chatroom!", new_chatroom_path, class: "btn btn-primary"

ul.users
	= render @chatrooms

app/views/chatrooms/new.html.slim
= provide(:title, 'Create a chatroom')
h1 Create a chatroom
.row
	.col-md-6.col-md-offset-3
		= form_for(@chatroom) do |f|
			- if @chatroom.errors.any?
				.alert the form contains #{pluralize(@chatroom.errors.count, 'error')}
				ul
					- @chatroom.errors.full_messages.each do |e|
						li #{e}
			/ = hidden_field_tag :user_id, current_user.id
			= f.label :topic
			= f.text_field :topic, class: "form-control"

			= f.submit "Create this chatroom", class: "btn btn-primary"

app/views/chatrooms/show.html.erb
<div class="row">
	<%=content_tag :div, '', class: "temp-info", data: { temp: current_user.id } %>
	<div class="col-md-8 col-md-offset-2">
	  <h1><%= @chatroom.topic %></h1>
		<div class="panel panel-default">
		  <p style="text-align: center;">Last 25 messages displayed only</p>
		  <% if @chatroom.messages.any? %>
		    <div class="panel-body" id="messages">
		      <%= render @chatroom.messages.for_display%>
		    </div>
		  <%else%>
		    <div class="panel-body hidden" id="messages">
		    </div>
		  <%end%>
		</div>

	  <%= render partial: 'messages/message_form'%>
	</div>
</div>