config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :users
  resources :chatrooms
  resources :messages
  resources :account_activation, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 	 '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'

  get 	 '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # mount ActionCable.server, at: '/cable'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-to">
  <div class="container">
    <%= link_to "UserApp", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Chatrooms", chatrooms_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>   

app/views/layouts/application.html.slim
doctype html
html

  head
    title = full_title(yield(:title))
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")    
      = yield
      = debug(params) if Rails.env.development?
      footer.center
        = link_to "@chandlerjwang", '#'